### ISSUE TITLE
Enforcing of bare repositories

### ISSUE THREAD

**Issue by alkuzad** [dancinglightning/gollum_rails#2]
Why there is an requirement to use bare git repository ? Gollum supports both bare and non-bare ones and it's impossible to see changes within bare repository.

**Comment by dancinglightning** [comment]
Please be aware that for historical reasons this code does not use gollum_lib . I believe florian has just released a new version of the gem and is working on the lib version again. https://github.com/nirnanaaa/gollum_rails

But as for using non-bare repositories: Changes made by the api will not update the working directory. That can be very confusing, so it's not encouraged

**Comment by alkuzad** [comment]
@dancinglightning oh exactly, I did not check the repo source of gem :) We are certainly using the Florian version but for some reason our dev linked to this docs source. Misleading ...

Does that mean this repository is no longer maintained and Florian is working on kind of fork ?

**Comment by dancinglightning** [comment]
strange, if you use florians code (version 1 or 3) , that should have his repo as homepage.

When i started with florian (note in readme) i was going to use a wiki. But then i never did.
The code is tested, but never used. I'll probably give it up soon.
There is someone else who did a git based wiki engine, but i forgot his name

**Comment by alkuzad** [comment]
Indeed it has, just someone sent link to this page on chat, probably due to googling
